import {
  app,
  BrowserWindow,
  session,
  desktopCapturer,
  ipcRenderer,
  ipcMain,
  contextBridge,
  globalShortcut,
  Notification,
} from "electron";
import * as fs from "fs";
import * as path from "path";
import crypto from "crypto";
import { Message, MessageLocal } from "./shared/types/message.type";
import { networkInterfaces } from "os";
import sound from "sound-play";
import { EndUser } from "./shared/types/enduser.type";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const createWindow = (partition: string): void => {
  // Create the browser window with unique session partition.
  const mainWindow = new BrowserWindow({
    height: 1080,
    width: 1800,
    autoHideMenuBar: true,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: true,
      contextIsolation: true,
      webSecurity: false,
      allowRunningInsecureContent: true,
      partition, // Unique partition for each window
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  // Handle screen sharing
  // mainWindow.webContents.on("did-finish-load", async () => {
  //   if (mainWindow) {
  //     desktopCapturer
  //       .getSources({ types: ["window", "screen"] })
  //       .then(async (sources) => {
  //         mainWindow.webContents.send("SEND_SCREEN_SHARE_SOURCES", sources);
  //       });
  //   }
  // });

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

app.on(
  "certificate-error",
  (event, webContents, url, error, certificate, callback) => {
    event.preventDefault();
    callback(true); // Trust the self-signed certificate
  },
);

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", () => {
  createWindow("persist:window1");
  createWindow("persist:window2");
  createWindow("persist:window3");
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow("persist:window1");
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
ipcMain.handle("GET_SCREEN_SHARE_SOURCES", () => {
  return desktopCapturer
    .getSources({ types: ["window", "screen"] })
    .then(async (sources) => {
      return sources;
    });
});
// Function to get the MAC address
function getMacAddress(): string {
  const interfaces = networkInterfaces();
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name] || []) {
      if (!iface.internal && iface.mac) {
        return iface.mac; // Return the MAC address of the first external interface
      }
    }
  }
  throw new Error("Unable to retrieve MAC address.");
}

// Derive a 32-byte key from the MAC address
function deriveEncryptionKey(macAddress: string): Buffer {
  return crypto.createHash("sha256").update(macAddress).digest();
}
ipcMain.handle(
  "SAVE_MESSAGE",
  async (event, userId: string, message: MessageLocal) => {
    const userDir = path.join(
      app.getPath("userData"),
      "messages",
      `${message.conversationId}-${userId}`,
    );
    if (!fs.existsSync(userDir)) {
      fs.mkdirSync(userDir, { recursive: true });
    }
    console.log("Messages directory:", userDir);
    console.log("Current file:", __filename);
    const messagesFile = path.join(
      userDir,
      `${message.conversationId}-${userId}.json`,
    );
    let messages = [];

    // Get MAC address and derive encryption key
    const macAddress = getMacAddress();
    const ENCRYPTION_KEY = deriveEncryptionKey(macAddress);
    const IV_LENGTH = 12; // Recommended IV length for GCM is 12 bytes

    // Encrypt message content
    const iv = crypto.randomBytes(IV_LENGTH);
    const cipher = crypto.createCipheriv("aes-256-gcm", ENCRYPTION_KEY, iv);

    let encryptedContent = cipher.update(message.content, "utf8");
    encryptedContent = Buffer.concat([encryptedContent, cipher.final()]);
    const authTag = cipher.getAuthTag();

    // Add encrypted content, IV, and auth tag to message
    if (fs.existsSync(messagesFile)) {
      const data = fs.readFileSync(messagesFile, "utf8");
      messages = JSON.parse(data);
    }

    const encryptedMessage = {
      ...message,
      _id: messages.length + 1,
      content: encryptedContent.toString("hex"),
      iv: iv.toString("hex"),
      authTag: authTag.toString("hex"),
    };

    messages.push(encryptedMessage);
    fs.writeFileSync(messagesFile, JSON.stringify(messages));
    return true;
  },
);

ipcMain.handle(
  "GET_MESSAGES",
  async (event, userId: string, conversationId: string) => {
    const messagesFile = path.join(
      app.getPath("userData"),
      "messages",
      `${conversationId}-${userId}`,
      `${conversationId}-${userId}.json`,
    );

    if (!fs.existsSync(messagesFile)) {
      return [];
    }
    const data: MessageLocal[] = JSON.parse(
      fs.readFileSync(messagesFile, "utf8"),
    );
    // Get MAC address and derive encryption key for decryption
    const macAddress = getMacAddress();
    const ENCRYPTION_KEY = deriveEncryptionKey(macAddress);

    // Decrypt each message
    const decryptedData = data.map((message) => {
      if (message.type === "file") {
        return message;
      } else {
        // Convert hex strings back to buffers
        const iv = Buffer.from(message.iv, "hex");
        const authTag = Buffer.from(message.authTag, "hex");
        const encryptedContent = Buffer.from(message.content, "hex");

        // Create decipher
        const decipher = crypto.createDecipheriv(
          "aes-256-gcm",
          ENCRYPTION_KEY,
          iv,
        );
        decipher.setAuthTag(authTag);

        // Decrypt
        let decryptedContent = decipher.update(encryptedContent);
        decryptedContent = Buffer.concat([decryptedContent, decipher.final()]);

        // Return message with decrypted content
        return {
          ...message,
          content: decryptedContent.toString("utf8"),
        };
      }
    });
    return decryptedData;
  },
);

ipcMain.handle(
  "SAVE_FILE",
  async (
    event,
    userSent: EndUser,
    userReceived: string,
    file: ArrayBuffer,
    conversationId: string,
  ) => {
    console.log("THE user IS", userReceived);
    const userDir = path.join(
      app.getPath("userData"),
      "messages",
      `${conversationId}-${userReceived}`,
    );
    if (!fs.existsSync(userDir)) {
      fs.mkdirSync(userDir, { recursive: true });
    }

    const messagesFile = path.join(
      userDir,
      `${conversationId}-${userReceived}.json`,
    );
    let messages = [];

    let fileBase64: any = file;
    // console.log("THE FILE IS", fileBase64)
    // if (typeof file !== "string") {
    //   console.log(fileBase64);
    //   // console.log("AM I HERE");
    //   fileBase64 = await getBase64(file);
    //   // console.log("the slice in AM I HERE", fileBase64.slice(0, 10));
    // } else {
    //   console.log("THE FILE BASE64 IS", fileBase64.slice(0, 10));
    // }
    // if (typeof file === "string") {
    //   console.log("THE FILE BASE64 IS", fileBase64.slice(0, 10));
    // }
    // if (fileBase64 === null || Object.keys(fileBase64).length == 0) {
    //   console.log("THE FILE BASE64 IS NULL");
    //   return false;
    // }
    if (fs.existsSync(messagesFile)) {
      const data = fs.readFileSync(messagesFile, "utf8");
      messages = JSON.parse(data);
    }

    const encryptedFile = {
      _id: messages.length + 1,
      content: fileBase64,
      endUserId: userSent,
      conversationId: conversationId,
      visibility: "normal",
      read: false,
      createdAt: new Date(),
      type: "file",
    };

    messages.push(encryptedFile);
    fs.writeFileSync(messagesFile, JSON.stringify(messages));
    return true;
  },
);

ipcMain.handle("GET_FILE", async (event, filePath: string) => {
  if (!fs.existsSync(filePath)) {
    throw new Error("File not found");
  }
  return fs.readFileSync(filePath);
});

ipcMain.handle("GET_USER_FILES", async (event, userId: string) => {
  const userDir = path.join(app.getPath("userData"), "files", userId);
  if (!fs.existsSync(userDir)) {
    return [];
  }
  return fs.readdirSync(userDir);
});

ipcMain.handle(
  "SHOW_NOTIFICATION",
  async (event, title: string, body: string, icon: string) => {
    const notif = new Notification({
      title,
      body,
      icon,
    });
    notif.on("click", () => {
      console.log("Thông báo đã được click!");
    });
    notif.show();
  },
);
