const ADD_POST_API_ENDPOINT = "/post";
const GET_POST_API_ENDPOINT = "/posts";
const GET_USER_CREATED_POSTS_API_ENDPOINT = "/posts/enduser/";
const GET_USER_LIKED_POSTS_API_ENDPOINT = "/posts/liked-posts/";
export {
  ADD_POST_API_ENDPOINT,
  GET_POST_API_ENDPOINT,
  GET_USER_CREATED_POSTS_API_ENDPOINT,
  GET_USER_LIKED_POSTS_API_ENDPOINT,
};
